import { afterEach, describe, expect, it, vi } from 'vitest';
import { selectMidtermChartData } from './chartSelectors';

function segment(booking_start, booking_end, category = 'pedagogical') {
  return { booking_start, booking_end, category };
}

function weekdaySegments(start, end) {
  return [
    { day: 1, day_name: 'Mo', segments: [segment(start, end)] },
    { day: 2, day_name: 'Di', segments: [segment(start, end)] },
    { day: 3, day_name: 'Mi', segments: [segment(start, end)] },
    { day: 4, day_name: 'Do', segments: [segment(start, end)] },
    { day: 5, day_name: 'Fr', segments: [segment(start, end)] },
  ];
}

describe('chartSelectors auto transition projection', () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  it('projects enabled auto transition events into midterm demand after the event month', () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-05-20T12:00:00Z'));

    const state = {
      simScenario: {
        selectedScenarioId: 'scenario-1',
        scenarios: [{ id: 'scenario-1', name: 'Szenario 1' }],
      },
      chart: {
        'scenario-1': {
          referenceDate: '2026-05-20',
          timedimension: 'month',
          filter: {
            Groups: [],
            Qualifications: [],
          },
        },
      },
      simOverlay: {
        overlaysByScenario: {},
      },
      simData: {
        dataByScenario: {
          'scenario-1': {
            child1: {
              id: 'child1',
              name: 'Mia',
              type: 'demand',
              startdate: '2026-01-01',
              enddate: '',
              dateofbirth: '2023-03-01',
            },
            employee1: {
              id: 'employee1',
              name: 'Alex',
              type: 'capacity',
              startdate: '2026-01-01',
              enddate: '',
            },
          },
        },
      },
      simBooking: {
        bookingsByScenario: {
          'scenario-1': {
            child1: {
              b1: {
                id: 'b1',
                startdate: '2026-01-01',
                enddate: '',
                times: weekdaySegments('08:00', '10:00'),
              },
            },
            employee1: {
              e1: {
                id: 'e1',
                startdate: '2026-01-01',
                enddate: '',
                times: weekdaySegments('08:00', '14:00'),
              },
            },
          },
        },
      },
      simGroup: {
        groupDefsByScenario: {
          'scenario-1': [],
        },
        groupsByScenario: {
          'scenario-1': {},
        },
      },
      simQualification: {
        qualificationAssignmentsByScenario: {
          'scenario-1': {},
        },
        qualificationDefsByScenario: {
          'scenario-1': [],
        },
      },
      simFinance: {
        financeByScenario: {
          'scenario-1': {},
        },
      },
      events: {
        eventsByScenario: {
          'scenario-1': [
            {
              id: 'auto_transition_school_child1',
              scenarioId: 'scenario-1',
              effectiveDate: '2026-09-01',
              type: 'auto_group_transition',
              category: 'auto_transition',
              entityType: 'demand',
              entityId: 'child1',
              entityName: 'Mia',
              description: 'Automatischer Gruppenwechsel: Kita → Schulkindbetreuung',
              metadata: {
                autoGenerated: true,
                targetStage: 'school',
                bookingDeltaHours: -5,
              },
              enabled: true,
            },
          ],
        },
      },
    };

    const result = selectMidtermChartData(state);
    const augustIndex = result.categories.indexOf('2026-08');
    const septemberIndex = result.categories.indexOf('2026-09');

    expect(augustIndex).toBeGreaterThanOrEqual(0);
    expect(septemberIndex).toBeGreaterThanOrEqual(0);
    expect(result.demand[augustIndex]).toBe(10);
    expect(result.demand[septemberIndex]).toBe(5);
    expect(result.child_count[augustIndex]).toBe(1);
    expect(result.child_count[septemberIndex]).toBe(1);
    expect(result.employee_count[augustIndex]).toBe(1);
    expect(result.employee_count[septemberIndex]).toBe(1);
    expect(result.child_count_by_group).toEqual([
      { groupId: '__NO_GROUP__', name: 'Ohne Gruppe', data: result.child_count },
    ]);
    expect(result.employee_count_by_group).toEqual([
      { groupId: '__NO_GROUP__', name: 'Ohne Gruppe', data: result.employee_count },
    ]);
  });

  it('excludes unknown-entity events from midterm timeline flags', () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-05-20T12:00:00Z'));

    const state = {
      simScenario: {
        selectedScenarioId: 'scenario-1',
        scenarios: [{ id: 'scenario-1', name: 'Szenario 1' }],
      },
      chart: {
        'scenario-1': {
          referenceDate: '2026-05-20',
          timedimension: 'month',
          filter: {
            Groups: [],
            Qualifications: [],
          },
        },
      },
      simOverlay: { overlaysByScenario: {} },
      simData: {
        dataByScenario: {
          'scenario-1': {
            child1: {
              id: 'child1',
              name: 'Mia',
              type: 'demand',
              startdate: '2026-01-01',
              enddate: '',
              dateofbirth: '2023-03-01',
            },
          },
        },
      },
      simBooking: {
        bookingsByScenario: {
          'scenario-1': {
            child1: {
              b1: {
                id: 'b1',
                startdate: '2026-01-01',
                enddate: '',
                times: weekdaySegments('08:00', '10:00'),
              },
            },
          },
        },
      },
      simGroup: {
        groupDefsByScenario: { 'scenario-1': [] },
        groupsByScenario: { 'scenario-1': {} },
      },
      simQualification: {
        qualificationAssignmentsByScenario: { 'scenario-1': {} },
        qualificationDefsByScenario: { 'scenario-1': [] },
      },
      simFinance: { financeByScenario: { 'scenario-1': {} } },
      events: {
        eventsByScenario: {
          'scenario-1': [
            {
              id: 'known-event',
              scenarioId: 'scenario-1',
              effectiveDate: '2026-09-01',
              type: 'auto_group_transition',
              category: 'auto_transition',
              entityType: 'demand',
              entityId: 'child1',
              entityName: 'Mia',
              description: 'Bekanntes Ereignis',
              metadata: { autoGenerated: true },
              enabled: true,
            },
            {
              id: 'unknown-event',
              scenarioId: 'scenario-1',
              effectiveDate: '2026-09-01',
              type: 'booking_start',
              category: 'booking',
              entityType: 'demand',
              entityId: 'orphan',
              entityName: 'Unbekannt',
              description: 'Orphan Ereignis',
              metadata: {},
              enabled: true,
            },
          ],
        },
      },
    };

    const result = selectMidtermChartData(state);
    const flagTexts = (result.flags || []).map((flag) => String(flag.text || ''));

    expect(flagTexts.some((text) => text.includes('Unbekannt'))).toBe(false);
    expect(flagTexts.some((text) => text.includes('Bekanntes Ereignis'))).toBe(true);
  });
});