import React from 'react';
import { Alert, Badge, Group, Paper, Stack, Switch, Text, ThemeIcon } from '@mantine/core';
import { IconCalendarEvent, IconInfoCircle } from '@tabler/icons-react';
import { useDispatch, useSelector } from 'react-redux';
import { useScenarioEvents } from '../../hooks/useScenarioEvents';
import { setEventEnabled } from '../../store/eventSlice';

function OrgaTabEvents() {
  const dispatch = useDispatch();
  const scenarioId = useSelector((state) => state.simScenario.selectedScenarioId);
  const { events } = useScenarioEvents(scenarioId);

  const groupedEvents = React.useMemo(() => {
    const today = new Date().toISOString().slice(0, 10);
    const relevantEvents = (events || []).filter(
      (event) => event.effectiveDate && (event.effectiveDate >= today || event.metadata?.autoGenerated)
    );

    const byDate = {};
    relevantEvents.forEach((event) => {
      if (!byDate[event.effectiveDate]) {
        byDate[event.effectiveDate] = [];
      }
      byDate[event.effectiveDate].push(event);
    });

    return Object.entries(byDate)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, grouped]) => ({ date, events: grouped }));
  }, [events]);

  if (!scenarioId) {
    return (
      <Alert icon={<IconInfoCircle size={16} />} color="blue" variant="light">
        Bitte zuerst ein Szenario auswählen.
      </Alert>
    );
  }

  return (
    <Stack gap="md">
      <Alert icon={<IconInfoCircle size={16} />} color="blue" variant="light">
        Automatisch erzeugte Gruppenwechsel sind markiert und können hier einzeln aktiviert oder deaktiviert werden.
      </Alert>

      {groupedEvents.length === 0 ? (
        <Paper withBorder p="md">
          <Text c="dimmed">Keine relevanten Ereignisse vorhanden.</Text>
        </Paper>
      ) : (
        groupedEvents.map((group) => (
          <Paper key={group.date} withBorder p="md" radius="md">
            <Stack gap="sm">
              <Group justify="space-between">
                <Group>
                  <ThemeIcon variant="light" color="blue">
                    <IconCalendarEvent size={16} />
                  </ThemeIcon>
                  <Text fw={600}>{group.date}</Text>
                </Group>
                <Badge variant="light">{group.events.length} Ereignisse</Badge>
              </Group>

              {group.events.map((event) => {
                const isAutomatic = event.metadata?.autoGenerated === true;
                return (
                  <Group key={event.id} justify="space-between" align="center" wrap="nowrap">
                    <div style={{ flex: 1 }}>
                      <Group gap="xs" mb={4}>
                        <Text fw={500}>{event.description}</Text>
                        <Badge size="xs" color={isAutomatic ? 'orange' : 'blue'} variant="light">
                          {isAutomatic ? 'Automatisch generiert' : 'Manuell/abgeleitet'}
                        </Badge>
                        {event.enabled === false && (
                          <Badge size="xs" color="gray" variant="outline">
                            deaktiviert
                          </Badge>
                        )}
                      </Group>
                      <Text size="sm" c="dimmed">
                        {event.entityName || 'Eintrag'}
                      </Text>
                    </div>

                    {isAutomatic ? (
                      <Switch
                        checked={event.enabled !== false}
                        onChange={(e) =>
                          dispatch(
                            setEventEnabled({
                              scenarioId,
                              eventId: event.id,
                              enabled: e.currentTarget.checked,
                            })
                          )
                        }
                        aria-label={`Ereignis ${event.description}`}
                      />
                    ) : (
                      <Badge size="sm" variant="outline" color="gray">
                        aktiv
                      </Badge>
                    )}
                  </Group>
                );
              })}
            </Stack>
          </Paper>
        ))
      )}
    </Stack>
  );
}

export default OrgaTabEvents;
