import React from 'react';
import { useSelector } from 'react-redux';
import { selectEventsForScenario } from '../store/eventSlice';
import { Group, Text, Card, Divider, SegmentedControl, Stack, Badge } from '@mantine/core';

function EventsView() {
  const selectedScenarioId = useSelector((state) => state.simScenario.selectedScenarioId);
  const events = useSelector((state) => selectEventsForScenario(state, selectedScenarioId));

  const [mode, setMode] = React.useState('all');

  // Filter events by auto/generated selection
  const filtered = React.useMemo(() => {
    return (events || []).filter((ev) => {
      if (mode === 'all') return true;
      if (mode === 'auto') return !!ev.metadata?.autoGenerated;
      if (mode === 'real') return !ev.metadata?.autoGenerated;
      return true;
    });
  }, [events, mode]);

  // Group by entityType (demand = child, capacity = staff) and then by entityName
  const byEntity = React.useMemo(() => {
    const map = {};
    (filtered || []).forEach((ev) => {
      const who = ev.entityType || 'other';
      if (!map[who]) map[who] = {};
      if (!map[who][ev.entityName]) map[who][ev.entityName] = [];
      map[who][ev.entityName].push(ev);
    });
    return map;
  }, [filtered]);

  return (
    <div>
      <Stack spacing="xs">
        <Text size="xl" fw={700}>Ereignisse</Text>
        <SegmentedControl
          value={mode}
          onChange={setMode}
          data={[
            { label: 'Alle', value: 'all' },
            { label: 'Automatisch', value: 'auto' },
            { label: 'Reale', value: 'real' },
          ]}
        />
      </Stack>
      <div style={{ marginTop: 12 }}>
        <Text color="dimmed">Gefiltert: <Badge>{filtered.length}</Badge></Text>
      </div>
      {Object.entries(byEntity).map(([entityType, items]) => (
        <div key={entityType} style={{ marginBottom: 16 }}>
          <Text fw={600} mb="xs">{entityType}</Text>
          <Divider />
          {Object.entries(items).map(([name, evs]) => (
            <Card key={name} withBorder shadow="xs" style={{ marginTop: 8 }}>
              <Group position="apart">
                <Text fw={700}>{name}</Text>
                <Text color="dimmed">{evs.length} Ereignisse</Text>
              </Group>
              <Divider my="sm" />
              {evs.map((ev) => (
                <div key={ev.id} style={{ padding: '6px 0' }}>
                  <Text size="sm">{ev.effectiveDate} — {ev.description || ev.type}</Text>
                </div>
              ))}
            </Card>
          ))}
        </div>
      ))}
    </div>
  );
}

export default EventsView;
