import React from 'react';
import { DatePickerInput } from '@mantine/dates';
import { useSelector, useDispatch } from 'react-redux';
import {
  setReferenceDate,
} from '../../store/chartSlice';
import { Drawer, Group, Text, Badge, ScrollArea, Divider } from '@mantine/core';
import { selectConsolidatedEventsForScenario } from '../../store/eventSlice';

function EventPicker({ scenarioId }) {
  const dispatch = useDispatch();
  const referenceDate = useSelector((state) => state.chart[scenarioId]?.referenceDate || null);
  const consolidated = useSelector((state) => selectConsolidatedEventsForScenario(state, scenarioId));
  const [drawerOpen, setDrawerOpen] = React.useState(false);

  // Build a Set of dates that have events for quick lookup
  const eventDates = React.useMemo(() => new Set((consolidated || []).map((g) => g.date)), [consolidated]);

  function handleChange(date) {
    const nextDate = date ? date.toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10);
    dispatch(setReferenceDate({ scenarioId, date: nextDate }));
  }

  function handleSelectEvent(date) {
    // date is ISO yyyy-mm-dd
    const d = new Date(date);
    handleChange(d);
    setDrawerOpen(false);
  }

  return (
    <>
      <DatePickerInput
        label="Stichtag"
        placeholder="Datum wählen"
        value={referenceDate ? new Date(referenceDate) : null}
        clearable={false}
        onFocus={() => setDrawerOpen(true)}
        onChange={(date) => handleChange(date)}
        // Render days with an indicator if there is an event on that date
        renderDay={(date) => {
          const iso = date.toISOString().slice(0, 10);
          const has = eventDates.has(iso);
          return (
            <div style={{ position: 'relative', width: '100%', height: '100%' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%' }}>
                {date.getDate()}
              </div>
              {has && (
                <div style={{ position: 'absolute', bottom: 4, left: '50%', transform: 'translateX(-50%)' }}>
                  <div style={{ width: 6, height: 6, borderRadius: 3, background: '#228be6' }} />
                </div>
              )}
            </div>
          );
        }}
      />

      <Drawer position="right" opened={drawerOpen} onClose={() => setDrawerOpen(false)} title="Ereignisse nach Datum" size="xs">
        <ScrollArea style={{ height: '70vh' }}>
          {(consolidated || []).map((group) => (
            <div key={group.date} style={{ paddingBottom: 12 }}>
              <Group position="apart" align="center">
                <Text fw={700}>{group.date}</Text>
                <Badge>{group.events.length}</Badge>
              </Group>
              <Divider my="xs" />
              {group.events.map((ev) => (
                <div key={ev.id} style={{ padding: '6px 0', cursor: 'pointer' }} onClick={() => handleSelectEvent(group.date)}>
                  <Group position="apart" align="center">
                    <div>
                      <Text size="sm">{ev.description || ev.entityName}</Text>
                      <Text size="xs" color="dimmed">{ev.entityType} — {ev.entityName}</Text>
                    </div>
                    {ev.metadata?.autoGenerated ? (
                      <Badge color="gray" variant="light">Auto</Badge>
                    ) : (
                      <Badge color="blue" variant="light">Real</Badge>
                    )}
                  </Group>
                </div>
              ))}
            </div>
          ))}
        </ScrollArea>
      </Drawer>
    </>
  );
}

export default EventPicker;
